##Overview

Dear Learner, 

Congratulations, you have studied Pandas all the way through the end of this bootcamp!!! This is the final graded hands-on exercise where you will be accomplishing the below mentioned task.

For the tasks, we'll be using the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University. You can find the orginal dataset here: https://github.com/CSSEGISandData/COVID-19


**Dataset Link**: https://raw.githubusercontent.com/dphi-official/Datasets/master/covid_19_data.csv

**Resources**: You may consider referring to this resource while solving this project: https://www.learndatasci.com/tutorials/python-pandas-tutorial-complete-introduction-for-beginners/

**Information about the dataset:**

There are 8 features:

* SNo: Serial number
* ObservationDate: Date of observation of the cases (format: MM/DD/YYYY)
* Province/State: Province or State of the country where cases were observed
* Country/Region: Country where cases were observed
* Last Update: Time in UTC at which the row is updated for the given province or country. (It is not in a standard format)
* Confirmed: Cumulative number of confirmed cases till the date
* Deaths: Cumulative number of deaths till the date
* Recovered: Cumulative number of recovered cases till date

**Instruction for the learner:** 
* Recommended to revise 'groupby()' method of pandas
* Recommended to understand the word **'Cummulative'** properly for three features - 'Confirmed', 'Recovered' and 'Deaths'.
* Please note that the dtype of datetime columns are of object, convert them to datetime as shown below:

###**Task 1**

* Read the dataset and name is as `df`
* Print first 10 observations of the dataset
* Check for the data types of the all the variables in the dataset
* Convert columns ['ObservationDate'] and ['Last Update'] to from object to datatime data type.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/covid_19_data.csv")

In [3]:
df.head(10)

   SNo ObservationDate Province/State  ... Confirmed Deaths  Recovered
0    1      01/22/2020          Anhui  ...       1.0    0.0        0.0
1    2      01/22/2020        Beijing  ...      14.0    0.0        0.0
2    3      01/22/2020      Chongqing  ...       6.0    0.0        0.0
3    4      01/22/2020         Fujian  ...       1.0    0.0        0.0
4    5      01/22/2020          Gansu  ...       0.0    0.0        0.0
5    6      01/22/2020      Guangdong  ...      26.0    0.0        0.0
6    7      01/22/2020        Guangxi  ...       2.0    0.0        0.0
7    8      01/22/2020        Guizhou  ...       1.0    0.0        0.0
8    9      01/22/2020         Hainan  ...       4.0    0.0        0.0
9   10      01/22/2020          Hebei  ...       1.0    0.0        0.0

[10 rows x 8 columns]

In [4]:
df.dtypes

SNo                  int64
ObservationDate     object
Province/State      object
Country/Region      object
Last Update         object
Confirmed          float64
Deaths             float64
Recovered          float64
dtype: object

In [5]:
df['ObservationDate']  = df['ObservationDate'] .astype('datetime64') 
df['Last Update']  = df['Last Update'].astype('datetime64')
df.dtypes

SNo                         int64
ObservationDate    datetime64[ns]
Province/State             object
Country/Region             object
Last Update        datetime64[ns]
Confirmed                 float64
Deaths                    float64
Recovered                 float64
dtype: object

### **Task 2**
* Create a subset of the data `df`, only taking observations which was **last updated** on **2020-06-13 03:33:14** and name this dataframe as **updated_data**. 
* Print the total no. of observations and unique country records in **updated_data**

In [7]:
updated_data = df[ df["Last Update"] =="2020-06-13 03:33:14"]
updated_data

         SNo ObservationDate      Province/State  ... Confirmed Deaths  Recovered
40076  40077      06/12/2020                 NaN  ...   23546.0  446.0     3928.0
40077  40078      06/12/2020                 NaN  ...    1416.0   36.0     1034.0
40078  40079      06/12/2020                 NaN  ...   10698.0  751.0     7322.0
40079  40080      06/12/2020                 NaN  ...     853.0   51.0      781.0
40080  40081      06/12/2020                 NaN  ...     130.0    5.0       42.0
...      ...             ...                 ...  ...       ...    ...        ...
40800  40801      06/12/2020           Zacatecas  ...     501.0   55.0      279.0
40801  40802      06/12/2020  Zakarpattia Oblast  ...    1506.0   38.0      675.0
40802  40803      06/12/2020   Zaporizhia Oblast  ...     515.0   15.0      322.0
40803  40804      06/12/2020            Zhejiang  ...    1268.0    1.0     1267.0
40804  40805      06/12/2020     Zhytomyr Oblast  ...    1013.0   17.0      527.0

[729 rows x 8 columns]

In [8]:
updated_data["Country/Region"].value_counts()

Russia                    83
US                        58
Japan                     48
India                     36
Colombia                  34
                          ..
Seychelles                 1
Togo                       1
Bosnia and Herzegovina     1
Sierra Leone               1
Saint Kitts and Nevis      1
Name: Country/Region, Length: 190, dtype: int64

In [9]:
updated_data["Country/Region"].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Austria',
       'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
       'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brunei', 'Bulgaria',
       'Burkina Faso', 'Burma', 'Burundi', 'Cabo Verde', 'Cambodia',
       'Cameroon', 'Central African Republic', 'Chad', 'Comoros',
       'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica', 'Croatia',
       'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Diamond Princess',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
       'Gambia', 'Georgia', 'Ghana', 'Greece', 'Grenada', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Holy See',
       'Honduras', 'Hungary', 'Iceland', 'Indonesia', 'Iran', 'Iraq',
       'Ireland', 'Israel', 'Ivory Coast', 'Jamaica', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos',
       'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Liechtenstein', 'Lithuania', 'Luxembourg', 'MS Zaandam',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Mauritania', 'Mauritius', 'Moldova', 'Monaco', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Namibia', 'Nepal',
       'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'North Macedonia', 'Norway', 'Oman', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Philippines', 'Poland', 'Portugal', 'Qatar',
       'Romania', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Somalia', 'South Africa', 'South Korea', 'South Sudan',
       'Sri Lanka', 'Sudan', 'Suriname', 'Switzerland', 'Syria', 'Taiwan',
       'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Uganda',
       'United Arab Emirates', 'Uruguay', 'Uzbekistan', 'Venezuela',
       'Vietnam', 'West Bank and Gaza', 'Western Sahara', 'Yemen',
       'Zambia', 'Zimbabwe', 'Italy', 'Brazil', 'Russia', 'Mexico',
       'Japan', 'US', 'Canada', 'Colombia', 'Peru', 'Spain', 'India',
       'UK', 'Mainland China', 'Chile', 'Australia', 'Pakistan',
       'Germany', 'Sweden', 'Ukraine', 'Hong Kong', 'Macau'], dtype=object)

### **Task 3**
* Create a subset of data from the dataframe **updated_data**, only taking the top 10 countries which have the maximum number of confirmed cases with features - **'Country/Region', 'Confirmed', 'Deaths' and 'Recovered'**. Name this dataframe as 'top_10'

* print the name of the countries in 'top_10' dataset
* Which country has the lowest number of confirmed cases among the ten countries in top_10 dataframe?
Hint: use groupby() to group all the observations with same country, sum all the observations and then sort the dataframe by confirmed cases.

In [11]:
top_10 = updated_data[["Country/Region", "Confirmed", "Deaths", "Recovered"]].sort_values(by="Confirmed", ascending = False).iloc[:10, :]
top_10

      Country/Region  Confirmed   Deaths  Recovered
40577             US   381714.0  30758.0        0.0
40556         Russia   202935.0   3187.0   118024.0
40131         France   188918.0  29315.0    69578.0
40148           Iran   182525.0   8659.0   144649.0
40233         Turkey   175218.0   4778.0   149102.0
40678         Brazil   167900.0  10368.0    49295.0
40574             US   166164.0  12489.0        0.0
40377             UK   156410.0  37069.0        0.0
40320             US   146659.0   4978.0        0.0
40437             US   131198.0   6260.0        0.0

In [15]:
top_10[["Country/Region"]]

      Country/Region
40577             US
40556         Russia
40131         France
40148           Iran
40233         Turkey
40678         Brazil
40574             US
40377             UK
40320             US
40437             US

In [37]:
top_10.groupby("Country/Region")[["Confirmed"]].sum().head(1)

                Confirmed
Country/Region
Brazil           167900.0

### **Task 4**
* Add two columns in 'top_10' dataframe - 'Recovered_percentage' and 'Deaths_percentage' 

where

'Recovered_percentage' = (Recovered cases / Confirmed cases) * 100

'Death_percentage' = (Deaths cases / Confirmed cases) * 100

* Print the top 3 countries with highest recovery precent

In [35]:
top_10['Recovered_percentage'] = top_10['Recovered'] / top_10['Confirmed'] * 100
top_10['Death_percentage'] = top_10['Deaths'] / top_10['Confirmed'] * 100
top_10

      Country/Region  Confirmed  ...  Recovered_percentage  Death_percentage
40577             US   381714.0  ...              0.000000          8.057865
40556         Russia   202935.0  ...             58.158524          1.570454
40131         France   188918.0  ...             36.829736         15.517314
40148           Iran   182525.0  ...             79.248870          4.744008
40233         Turkey   175218.0  ...             85.095139          2.726889
40678         Brazil   167900.0  ...             29.359738          6.175104
40574             US   166164.0  ...              0.000000          7.516068
40377             UK   156410.0  ...              0.000000         23.699891
40320             US   146659.0  ...              0.000000          3.394268
40437             US   131198.0  ...              0.000000          4.771414

[10 rows x 6 columns]

In [36]:
top_10.nlargest(3,'Recovered_percentage').head(3)

      Country/Region  Confirmed  ...  Recovered_percentage  Death_percentage
40233         Turkey   175218.0  ...             85.095139          2.726889
40148           Iran   182525.0  ...             79.248870          4.744008
40556         Russia   202935.0  ...             58.158524          1.570454

[3 rows x 6 columns]

##**Scores**

Each of the tasks is of 5 mark each and the scores will be given accordingly after the notebook review.